apiVersion: apps/v1
kind: Deployment
metadata:
  name: text2video-api
  labels:
    app: text2video-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text2video-api
  template:
    metadata:
      labels:
        app: text2video-api
    spec:
      containers:
      - name: api
        image: varunsoni94/text2video-api
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
          requests:
            memory: 2Gi
            cpu: "1"
        volumeMounts:
        - mountPath: /mnt/data/output
          name: output-volume
        - mountPath: /mnt/mochi-models
          name: mochi-cache-volume
      volumes:
      - name: output-volume
        hostPath:
          path: /mnt/data/output
          type: DirectoryOrCreate
      - name: mochi-cache-volume
        hostPath:
          path: /var/lib/mochi-models
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: text2video-api-service
spec:
  selector:
    app: text2video-api
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
