apiVersion: apps/v1
kind: Deployment
metadata:
  name: text2video-frontend
  labels:
    app: text2video-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text2video-frontend
  template:
    metadata:
      labels:
        app: text2video-frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: frontend
          image: varunsoni94/text2video-frontend
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: text2video-frontend-service
  labels:
    app: text2video-frontend
spec:
  selector:
    app: text2video-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
